org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

neoForge.parchment.minecraftVersion=1.21.1
neoForge.parchment.mappingsVersion=2024.09.03

mod_id=ntgl
mod_name=NTGL
archive_base_name=NTGL
mod_version=3.1.4
mod_group_id=com.nukateam.ntgl
minecraft_version=1.21.1
minecraft_version_range=[1.21.1, 1.21.2)
neo_version=21.1.209
loader_version_range=[1,)

mod_license=LGPL-2.1
mod_authors=Jetug, Dayton
mod_description=Core for weapons mods

neogradle.subsystems.parchment.minecraftVersion=1.21.1
neogradle.subsystems.parchment.mappingsVersion=2024.11.17

framework_file_id=5180972
curios_version=5.4.2+1.20.1
configured_file_id=5180900
catalogue_file_id=4766090
backpacked_file_id=4725669
controllable_file_id=4598985
simple_planes_file_id=4893679
recruits_file_id=4846123
sop_core_file_id=4993651
sop_backpacks_file_id=4993659
travelers_backpack_file_id=4985852
l2_lib_file_id=5179254
l2_backpack_file_id=5107073
jei_version=15.20.0.106

creativecore_file_id=5056178
cmdcam_file_id=5019847
