modLoader="javafml"
loaderVersion="[40,)"
license="LGPL 2.1"

[[mods]]
modId="ntgl"
version="3.0.0"
displayName="NukaTeam's Gun Lib"
updateJSONURL=""
displayURL="https://discord.com/invite/njb6EKaDVJ"
logoFile="logo.png"
authors="Dayton, Jetug"
credits = "MrCrayfish, MigaMi"
description="Core for gun mods"
[[dependencies.ntgl]]
modId="forge"
mandatory=true
versionRange="[46, 48)"
ordering="NONE"
side="BOTH"
[[dependencies.ntgl]]
modId="minecraft"
mandatory=true
versionRange="[1.20, 1.20.2)"
ordering="NONE"
side="BOTH"
[[dependencies.ntgl]]
modId="framework"
mandatory=true
versionRange="[0.6.16,)"
ordering="NONE"
side="BOTH"
[[dependencies.ntgl]]
modId="geckolib"
mandatory=true
versionRange="[4.8.2,)"
ordering="AFTER"
side="BOTH"
[[dependencies.ntgl]]
modId="controllable"
mandatory=false
versionRange="[0.16.3,)"
ordering="AFTER"
side="CLIENT"
[[dependencies.ntgl]]
modId="backpacked"
mandatory=false
versionRange="[3.0.0-beta.9,)"
ordering="AFTER"
side="BOTH"
[[dependencies.ntgl]]
modId="jei"
mandatory=false
versionRange="[12.1.1,)"
ordering="AFTER"
side="CLIENT"

[modproperties.ntgl]
    catalogueImageIcon=""
