modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="NukaTeam's Gun Lib"
displayURL="https://discord.com/invite/njb6EKaDVJ"
logoFile="logo.png"
authors="Jetug, Dayton"
credits = "MrCrayfish, MigaMi"
description="Core for weapon mods"

[[accessTransformers]]
file="META-INF/accesstransformer.cfg"

[[mixins]]
config = "ntgl.mixin.json"

[[dependencies."${mod_id}"]]
modId="neoforge"
mandatory=true
versionRange="[${neo_version},)"
ordering="NONE"
side="BOTH"
[[dependencies."${mod_id}"]]
modId="minecraft"
mandatory=true
versionRange="${ minecraft_version_range"
ordering="NONE"
side="BOTH"
[[dependencies."${mod_id}"]]
modId="geckolib"
mandatory=true
versionRange="[4.8.2,)"
ordering="AFTER"
side="BOTH"
[[dependencies."${mod_id}"]]
modId="jei"
mandatory=false
versionRange="[12.1.1,)"
ordering="AFTER"
side="CLIENT"
#[[dependencies."${mod_id}"]]
#modId="controllable"
#mandatory=false
#versionRange="[0.16.3,)"
#ordering="AFTER"
#side="CLIENT"

[modproperties.ntgl]
    catalogueImageIcon=""
